server:
  port: 23309
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cs309a
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # replace ${DB_USERNAME} and ${DB_PASSWORD} with your own username and password
    # or set environment variables


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 159MB

#    path: /api

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


