server:
  port: 23309
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cs309a
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # replace ${DB_USERNAME} and ${DB_PASSWORD} with your own username and password
    # or set environment variables
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    open-in-view: true


