server:
  port: 23309
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cs309a
    username: postgres
    password: Qq1754479362
    # replace ${DB_USERNAME} and ${DB_PASSWORD} with your own username and password
    # or set environment variables
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true



    open-in-view: true


